# ---- Order State ----
ORDER_CHOOSE_PAYMENT  = 1
ORDER_WAIT_SELLER     = 2
ORDER_WAIT_PAY        = 3
ORDER_WAIT_SHIP       = 4
ORDER_SHIPPED         = 5
ORDER_RECEIVED        = 6
ORDER_REJECT_STOCK    = 7
ORDER_REJECT_RATING   = 8
ORDER_REJECT_TIMEOUT  = 9
ORDER_REJECT_FAILED   = 10
ORDER_CANCELLED       = 11


# ---- Payment State ----
PAY_CASH_ON_DELIVERY  = 1
PAY_WAIT_DEPOSIT      = 2
PAY_DEPOSITED         = 3
PAY_WAIT_FINAL        = 4
PAY_FINAL_PAID        = 5
PAY_WAIT_EXTRA        = 6
PAY_ALL_PAID          = 7
PAY_WAIT_FULL         = 8
PAY_FULL_PAID         = 9
PAY_WAIT_SELECT       = 10
PAY_CANCELLED         = 11
