"""
Django settings for goodBuy project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

USE_CELERY = os.environ.get('USE_CELERY', '1') == '1'
# 不測試自動新增訂單不啟動
# 使用： set USE_CELERY=1


# MEDIA_URL = '/upload/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'upload')

# User更改
AUTH_USER_MODEL = 'goodBuy_web.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!   
SECRET_KEY = 'django-insecure-88zyj%-(9nahss0$fz$h=j#m!ry_6l-f+hfr912_v5f*g#x9=8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '.trycloudflare.com'
    'goodbuy.com', 
    'www.goodbuy.com', 
    '127.0.0.1', 
    'localhost',
    'goodbuy.duckdns.org',
    'gray-occupational-provided-favorite.trycloudflare.com']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO','https')
CSRF_TRUSTED_ORIGINS = ['https://goodbuy.duckdns.org',
                        'https://*.trycloudflare.com']
CSRF_COOKUE_SECURE = True
SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'goodBuy_web.apps.GoodBuyWebConfig',
    'goodBuy_shop',
    'goodBuy_order',
    'goodBuy_want',
    'goodBuy_tag',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'goodBuy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goodBuy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用 MySQL 作为数据库
        'NAME': '114-509',         # 数据库名称
        'USER': '114509',         # 数据库用户名
        'PASSWORD': 'Ntubimd_1145@9', # 数据库密码
        'HOST': '140.131.114.242',                  # 数据库服务器地址，远程服务器需填写 IP
        'PORT': '3306',                        # MySQL 端口号（默认 3306）
        'OPTIONS': {
            'charset': 'utf8mb4',  # 解决存储中文字符问题
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # 路徑
]

STATIC_ROOT = BASE_DIR / 'staticfiles'  # 路徑
STATICFILES_STORAGE = "whitenoise.storage.CompressedMaifestStaticFilesStorage"

MEDIA_URL = '/upload/'
MEDIA_ROOT = BASE_DIR / 'upload'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Celery 設定 ---
if USE_CELERY:
    CELERY_BROKER_URL = 'redis://localhost:6379/0'
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'Asia/Taipei'
    CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

    CELERY_BEAT_SCHEDULE = {
        'auto-settle-rush-every-minute': {
            'task': 'goodBuy_order.tasks.auto_settle_rush_orders',
            'schedule': crontab(),
        },
    }
