# Generated by Django 4.2.5 on 2025-08-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_order', '0031_alter_cart_update_alter_orderpayment_seller_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intentproduct',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='intentproduct',
            constraint=models.UniqueConstraint(fields=('intent', 'product'), name='uniq_intent_product'),
        ),
        migrations.AddConstraint(
            model_name='intentproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='qty_nonnegative'),
        ),
    ]
