# Generated by Django 4.2.5 on 2025-09-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodBuy_order', '0032_alter_intentproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
