# Generated by Django 5.1.7 on 2025-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodBuy_shop', '0027_shoprecommendationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
